export const loading = state => state.loading;
export const ajaxLoading = state => state.ajaxLoading;
export const playTpl = state => state.playTpl;
export const playName = state => state.currentPlay.title;
export const dropping = state => state.dropping;
export const dropEl = state => state.dropEl;
export const currentPlay = state => state.currentPlay;
export const showLogin = state => state.showLogin;
export const playType = state => state.playType;
export const currentLottery = state => state.currentLottery;
export const selectedLottery = state => state.selectedLottery;
export const user = state => state.user;
export const explainFlag = state => state.explainFlag;
export const beishu = state => state.beishu;
export const calcFun = state => state.calcFun;
export const totalCount = state => state.totalCount;
export const totalPrice = state => state.totalCount * state.beishu;
